version: '2'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:6666
    volumes:
      - .:/code
    ports:
      - "6666:6666"
  benchmark:
    build: .
    command: ./wrk/wrk -t12 -c400 -d30s http://192.168.99.100:6666/query?airport_address=2100%20NW%2042nd%20Ave.%20Miami,%20Fl&hotel_name=Coral+Creek+Plaza
    links:
      - web
  coverage:
    build: .
    command: coverage run --source='.' manage.py test
  report:
    build: .
    command: coverage report
    links:
      - coverage